[package]
name = "typst2mathjax"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
typst = {git = "https://github.com/typst/typst.git"}
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itertools = "0.12"
wasm-bindgen = "0.2"